Update city_of_kingston.json
openaddresses/openaddresses pull request #5382
Opened 2020-09-23 16:49 UTC by KHobbs3

Updated data links and added license information.

2020-09-23 18:00 UTC, iandees requested changes

2020-09-23 18:00 UTC, iandees commented on sources/ca/on/city_of_kingston.json
> +                "data": "https://opendatakingston.cityofkingston.ca/explore/dataset/civic-addresses/download/?format=geojson&timezone=America/New_York&lang=en",
Looks like you're asking to download it as geojson but specify a format of "shapefile" below.

2020-09-29 13:09 UTC, JosephKuchar commented
Looks like the issue may be the column names. I'm looking at the geojson, these are the variables:

"address_number"
"street"
"postal_code"
"unit"

Probably there's an inconsistency between the csv column names and geojson column names.

2020-09-29 13:47 UTC, JosephKuchar commented
Looking at the log from data-pls, it looks like it is having issues with the geojson:

2020-09-29 13:16:54,820   DEBUG: Content-Type says "application/json" for https://opendatakingston.cityofkingston.ca/explore/dataset/civic-addresses/download/?format=geojson&timezone=America/New_York&lang=en
2020-09-29 13:16:54,820   DEBUG: Content-Disposition disagrees: "civic-addresses.geojson"
2020-09-29 13:16:54,823 WARNING: Error in process_one.process()
Traceback (most recent call last):

Maybe @iandees or @ingalls can tell what's going on. I downloaded the csv to see if it would be better, but it's also a bit weirdly formatted.

2023-09-12 16:26 UTC, arch0345 commented
Superseded by #6943

2023-09-12 16:26 UTC, closed without merging